name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set NX sha
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - name: NPM clean install
        run: npm ci

      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
